import { chooseAge, openResults, openSearch, revealPreferences } from "./ui-helpers.mjs";
import {test,expect} from '@playwright/test';
import {createAPI} from '../../server/api.mjs';
import {fixtureCatalog} from '../../server/fixtures.mjs';
import {mkdirSync} from 'node:fs';
const out=process.env.QA_EVIDENCE_DIR||'.build/price-registration';mkdirSync(out,{recursive:true});
test('short-stay price changes result/map/comparison priority and registration icons reveal their actual sources',async({page})=>{
  const source={url:'https://example.com/fee-source',label:'Test source',retrievedAt:'2026-09-13'},base=fixtureCatalog.items[0];
  const items=[['higher',60,'hour',true],['budget',40,'hour',false],['lowest',30,'hour',null],['unknown',1,'month',null],['conflict',5,'hour',null]].map(([id,amount,basis,official],i)=>({...structuredClone(base),id,name:`Test ${id}`,mode:'live',location:{lat:3.139+i*.001,lng:101.6869},feeRule:null,
    fees:[{amount,currency:'MYR',basis,kind:'programme',verification:'provider_published',conditions:'Test programme',source},{amount:500,currency:'MYR',basis:'month',kind:'programme',source}],admission:{...base.admission,value:id!=='conflict'},
    registration:{...base.registration,authority:official?'JKM':'KPM',number:official===null?null:official?'JKM-TEST':'KPM-TEST',official:official===true,match:'existing_registered_record',source}}));
  const api=createAPI({store:{catalog:async()=>({...fixtureCatalog,items})},drivingRoutes:async(_,rows)=>rows.map(p=>({...p,driving:{state:'available',minutes:8,distanceKm:3}}))});
  await page.route('**/api',async route=>route.fulfill({json:{ok:true,...await api(route.request().postDataJSON())}}));
  await page.addInitScript(()=>{
    localStorage.setItem('equalpath:tour:v1','{"version":1,"status":"skipped"}');
    localStorage.setItem('equalpath:map:v1:live',JSON.stringify({version:1,zoom:13,center:{lat:3.139,lng:101.6869},pickup:{id:null,label:'KL centre',lat:3.139,lng:101.6869}}));
  });
  await page.goto('/?care=short_term#discover');await openSearch(page);await page.locator('#service-date').fill('2026-09-14');await page.locator('#deadline').fill('16:00');await page.locator('#care-end').fill('17:00');await revealPreferences(page); await page.locator('#transport').selectOption('self');await chooseAge(page); await page.getByRole('button',{name:'Find childcare',exact:true}).click();await openResults(page);
  await expect(page.locator('.provider-row').first()).toHaveAttribute('data-provider-id','higher');
  await page.getByRole('combobox',{name:'Order search results',exact:true}).click();await page.getByRole('option',{name:'Lowest fee',exact:true}).click();
  await expect(page.locator('.provider-row').first()).toHaveAttribute('data-provider-id','lowest');
  expect(await page.locator('.provider-row').evaluateAll(xs=>xs.map(x=>x.dataset.providerId))).toEqual(['lowest','budget','higher','unknown','conflict']);
  await expect(page.locator('#card-budget')).toContainText('MYR 40 / hour');
  await expect(page.locator('.provider-row').filter({hasText:'/ month'})).toHaveCount(0);
  await expect(page.locator('#card-unknown .row-facts').last()).toContainText('Ask the centre');
  expect(await page.locator('.provider-pin.suggested').evaluateAll(xs=>xs.map(x=>x.dataset.providerId).sort())).toEqual(['budget','higher','lowest']);
  await expect(page.locator('.provider-pin')).toHaveCount(5);
  const conflictPin=page.locator('.provider-pin.conflict');await expect(conflictPin).toHaveCount(1);await expect(conflictPin).toHaveAttribute('data-provider-id','conflict');
  await expect(conflictPin).toHaveAttribute('aria-description',/don’t match/);
  expect(await conflictPin.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(await page.locator('.provider-pin[data-provider-id="unknown"]').evaluate(el=>getComputedStyle(el).backgroundColor));
  await conflictPin.click();await expect(conflictPin).toHaveAttribute('aria-pressed','true');
  await openResults(page);
  await expect(page.getByRole('button',{name:'Select Test conflict',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#card-lowest .registration-badge')).toHaveCount(0);
  await page.locator('#card-budget .row-facts').last().click();
  await expect(page.getByRole('button',{name:'Select Test budget',exact:true})).toHaveAttribute('aria-pressed','true');
  const registered=page.getByRole('button',{name:'Listed in JKM register for Test higher'});await registered.click();
  await expect(registered.locator('svg')).toHaveAttribute('class',await page.locator('#card-budget .registration-badge svg').getAttribute('class'));
  await expect(page.getByRole('region',{name:'Registration record'})).toContainText('JKM-TEST');
  await expect(page.getByRole('region',{name:'Registration record'}).getByRole('link')).toHaveAttribute('href',source.url);
  await page.keyboard.press('Escape');await expect(registered).toBeFocused();await expect(registered).toHaveAttribute('aria-expanded','false');
  await page.getByRole('button',{name:'KPM code listed for Test budget'}).click();
  await expect(page.getByRole('region',{name:'Registration record'})).toContainText('not been independently checked');
  await page.locator('#card-budget').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/price-badge-desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.locator('#card-budget').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/price-badge-mobile.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.keyboard.press('Escape');
  for(const id of ['higher','budget','lowest'])await page.getByRole('button',{name:`Compare Test ${id}`,exact:true}).click();
  await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:/Compare/}).click();
  await expect(page.getByRole('combobox',{name:'Comparison priority'})).toHaveText('Nearest first');
  await expect(page.getByRole('dialog')).not.toContainText(/straight.line/i);
  await page.getByRole('button',{name:'More details',exact:true}).click();
  const locations=page.locator('.comparison-scroll tr').filter({has:page.getByText('Address',{exact:true})});
  await expect(locations).toHaveCount(1);
  await expect(locations).not.toContainText(/\bkm\b/);
  await expect(page.locator('.comparison-scroll tr[data-fact="drive"]')).toContainText('About 8 min');
  await expect(page.locator('.comparison-scroll')).not.toContainText('/ month');
  await page.getByRole('combobox',{name:'Comparison priority',exact:true}).click();await page.getByRole('option',{name:'Lowest fee',exact:true}).click();
  await expect(page.locator('th.comparison-best')).toHaveCount(1);await expect(page.locator('th.comparison-best')).toHaveAttribute('data-provider-id','lowest');
  await expect(page.locator('.comparison-best-tag')).toHaveText('Lowest hourly fee');
  await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.getByRole('button',{name:'View details for Test unknown',exact:true}).click();
  await expect(page.locator('.metric-fee')).toContainText('Ask the centre');
  await expect(page.locator('.metric-fee')).not.toContainText('Area budget');
  await expect(page.locator('.centre-fees')).not.toContainText('/ month');
  await expect(page.locator('.centre-fees')).toContainText('Ask the centre for a quote');
});

test('nearby conflicts stay in a full 10-centre page and remain selectable on the map',async({page})=>{
  const base=fixtureCatalog.items[0],items=Array.from({length:26},(_,i)=>({...structuredClone(base),id:`near-${i}`,name:`Nearby ${i}`,location:{lat:3.139+i*.001,lng:101.6869+(i%3)*.001},feeRule:null,fees:[{amount:1000-i*10,currency:'MYR',basis:'hour',kind:'programme'}],admission:{...base.admission,value:i!==0}}));
  const api=createAPI({store:{catalog:async()=>({...fixtureCatalog,items})},drivingRoutes:async(_,rows)=>rows.map(p=>({...p,driving:{state:'available',minutes:8,distanceKm:3}}))});
  await page.route('**/api',async route=>route.fulfill({json:{ok:true,...await api(route.request().postDataJSON())}}));
  await page.addInitScript(()=>{
    localStorage.setItem('equalpath:tour:v1','{"version":1,"status":"skipped"}');
    localStorage.setItem('equalpath:map:v1:live',JSON.stringify({version:1,zoom:13,center:{lat:3.139,lng:101.6869},pickup:{id:null,label:'KL centre',lat:3.139,lng:101.6869}}));
  });
  await page.goto('/?care=short_term#discover');await openSearch(page);await page.locator('#service-date').fill('2026-09-14');await page.locator('#deadline').fill('16:00');await page.locator('#care-end').fill('17:00');await revealPreferences(page); await page.locator('#transport').selectOption('self');await chooseAge(page); await page.getByRole('button',{name:'Find childcare',exact:true}).click();await openResults(page);
  await expect(page.locator('.provider-row')).toHaveCount(10);
  await expect(page.locator('.provider-row').last()).toHaveAttribute('data-provider-id','near-0');
  const firstIds=await page.locator('.provider-row').evaluateAll(xs=>xs.map(x=>x.dataset.providerId).sort());
  expect(firstIds).toEqual(items.slice(0,10).map(p=>p.id).sort());
  await expect(page.locator('.provider-pin')).toHaveCount(10);
  const conflictPin=page.locator('.provider-pin.conflict');await expect(conflictPin).toHaveCount(1);
  await conflictPin.click();await expect(conflictPin).toHaveAttribute('aria-pressed','true');
  await openResults(page);
  await expect(page.getByRole('button',{name:'Select Nearby 0',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('combobox',{name:'Order search results',exact:true}).click();await page.getByRole('option',{name:'Lowest fee',exact:true}).click();
  await expect(page.locator('.provider-row').first()).toHaveAttribute('data-provider-id','near-9');
  expect(await page.locator('.provider-row').evaluateAll(xs=>xs.map(x=>x.dataset.providerId).sort())).toEqual(firstIds);
  await expect(page.locator('.provider-row').last()).toHaveAttribute('data-provider-id','near-0');
  await page.getByRole('button',{name:'Why this order?',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('next 10 nearest centres');
  await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.locator('#card-near-0').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/nearest-page-conflict-desktop.png'});
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await expect(page.locator('.provider-row')).toHaveCount(10);
  await expect(page.locator('.pagination')).toContainText('11–20 / 26');
  expect(await page.locator('.provider-row').evaluateAll(xs=>xs.map(x=>x.dataset.providerId).sort())).toEqual(items.slice(10,20).map(p=>p.id).sort());
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await expect(page.locator('.provider-row')).toHaveCount(6);
  await expect(page.locator('.pagination')).toContainText('21–26 / 26');
  await expect(page.getByRole('button',{name:'Next',exact:true})).toBeDisabled();
  expect(await page.locator('.provider-row').evaluateAll(xs=>xs.map(x=>x.dataset.providerId).sort())).toEqual(items.slice(20).map(p=>p.id).sort());
  await page.getByRole('button',{name:'Previous',exact:true}).click();await expect(page.locator('.provider-row')).toHaveCount(10);
  await page.getByRole('button',{name:'Previous',exact:true}).click();
  await expect(page.locator('.pagination')).toContainText('1–10 / 26');
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Close search panel'}).click();
  await expect(page.locator('.provider-pin.conflict')).toHaveCount(1);
  await page.screenshot({path:out+'/nearest-page-conflict-mobile.png'});
});
