import { source } from "./providers.mjs";
const s = source(
  "Controlled example — fictional facts",
  null,
  "2026-09-12",
  null,
  "demo",
);
const w = (start, end) => ({
  days: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
  start,
  end,
  source: s,
});
const base = {
  region: "Kuala Lumpur",
  district: "Kuala Lumpur",
  mode: "demo",
  version: "demo-p03-v1",
  category: "TADIKA",
  address: "Illustrative public location in Kuala Lumpur",
  addressSource: s,
  registration: {
    authority: "JKM",
    number: "DEMO-001",
    category: "Controlled example",
    publishedName: "FICTIONAL LEARNING HOUSE",
    from: "2025-01-01",
    until: "2028-12-31",
    match: "demo_match",
    official: false,
    source: s,
    missingImportedFields: ["postal address", "telephone"],
    matchBasis: "Fictional identity for repeatable testing only.",
    warnings: [],
  },
  phone: null,
  website: null,
  sourcePage: null,
  age: {
    min: 24,
    max: 72,
    endpointKnown: true,
    maxInclusive: false,
    wording: "2 years to under 6 years (controlled example)",
    source: s,
  },
  admission: {
    value: true,
    wording: "One-off temporary care is described in this controlled example.",
    source: s,
  },
  transport: {
    exists: true,
    type: "Institution-operated",
    wording: "Institution-operated pickup (controlled example).",
    coverage: {
      placeIds: ["demo-pickup"],
      exhaustive: true,
      wording: "Covers the selected Demo pickup centre only.",
      source: s,
    },
    source: s,
  },
  pickupWindows: [w(900, 930)],
  careWindows: [w(900, 1140)],
  businessHours: { windows: [w(480, 1140)], closedDays: [], source: s },
  dateExceptions: [],
  lateRule: { latestEnd: 1140, source: s },
  fees: [
    {
      amount: 18,
      currency: "MYR",
      basis: "hour",
      kind: "temporary_care",
      conditions:
        "Two-hour minimum; all listed extras included. Controlled example only.",
      source: s,
    },
  ],
  feeRule: {
    validated: true,
    complete: true,
    basis: "hour",
    rate: 18,
    currency: "MYR",
    minimumMinutes: 120,
    roundingMinutes: 30,
    includedExtras: [
      "Meals",
      "Materials",
      "Registration",
      "Transport",
      "No late surcharge within the stated window",
    ],
    transportIncluded: true,
    source: s,
  },
  notes: ["Fictional provider. Do not use these details to arrange real care."],
  sources: [s],
};
export const demoPickup = {
  id: "demo-pickup",
  label: "Demo usual centre · Kuala Lumpur",
  lat: 3.139,
  lng: 101.6869,
  region: "Kuala Lumpur",
};
export const fixtureProviders = [
  {
    ...structuredClone(base),
    id: "demo-garden",
    name: "Demo · Garden Learning House",
    registeredName: "FICTIONAL GARDEN",
    location: { lat: 3.143, lng: 101.688, source: s },
  },
  {
    ...structuredClone(base),
    id: "demo-river",
    name: "Demo · Riverside Care",
    registeredName: "FICTIONAL RIVERSIDE",
    location: { lat: 3.134, lng: 101.69, source: s },
    pickupWindows: [w(990, 1020)],
    careWindows: [w(780, 1020)],
    lateRule: { latestEnd: 1020, source: s },
    businessHours: { windows: [w(480, 1020)], closedDays: [], source: s },
    registration: { ...base.registration, until: "2020-12-31" },
    fees: [
      {
        amount: 850,
        currency: "MYR",
        basis: "month",
        source: s,
        conditions: "Monthly enrolment; temporary charges unspecified.",
      },
    ],
    feeRule: null,
  },
  {
    ...structuredClone(base),
    id: "demo-cloud",
    name: "Demo · Cloud Care Studio",
    registeredName: "FICTIONAL CLOUD",
    location: null,
    age: {
      min: 54,
      max: 72,
      endpointKnown: true,
      wording: "54 months to under 72 months",
      source: s,
    },
    admission: {
      value: null,
      wording:
        "A monthly programme is described; temporary admission is unspecified.",
      source: s,
    },
    transport: {
      exists: true,
      type: "Partner transport",
      wording: "Transport is advertised, without a published service area.",
      coverage: null,
      source: s,
    },
    pickupWindows: [w(930, 990)],
    careWindows: [],
    lateRule: null,
    businessHours: { windows: [], closedDays: [], source: s },
    fees: [],
    feeRule: null,
    registration: {
      ...base.registration,
      authority: "KPM",
      number: "DEMO-CODE",
      match: "third_party_code_claim",
      official: false,
    },
  },
  {
    ...structuredClone(base),
    id: "demo-garden-branch",
    name: "Demo · Garden Learning House — other branch",
    registeredName: "FICTIONAL GARDEN OTHER BRANCH",
    location: { lat: 3.148, lng: 101.681, source: s },
    transport: {
      exists: false,
      type: null,
      wording: "This branch explicitly does not offer pickup.",
      source: s,
    },
    admission: {
      value: false,
      wording: "This branch offers monthly enrolment only.",
      source: s,
    },
    pickupWindows: [],
    fees: [],
    feeRule: null,
    registration: {
      ...base.registration,
      number: null,
      match: "unresolved",
      matchBasis: "Same brand name; branch identity is unresolved.",
    },
  },
];
export const fixtureCatalog = {
  items: fixtureProviders,
  held: [],
  version: "demo-p03-v1",
  release: "demo-p03-v1",
};
