import React from "react";
import { createRoot } from "react-dom/client";
import Experience from "./Experience.jsx";
import "maplibre-gl/dist/maplibre-gl.css";
import "./fonts.css";
import "./styles.css";
import "./preparation.css";
import "./interactions.css";
import "./ease.css";
import "./map-discovery.css";
import "./map-search-dock.css";
import "./map-glass.css";
import "./surfaces.css";
import "./comparison.css";
import "./recommendations.css";
createRoot(document.getElementById("root")).render(<Experience />);
